$import("mx.containers.HSplit");$import("mx.containers.Container");$import("mx.controls.ToolBar");$import("mx.datacontrols.DataGrid");$import("mx.datacontainers.GridEntityContainer");$import("mx.datacontrols.PageNaviBar");$import("mx.windows.Window");$import("rguser.views.MUserGridView");$import("rguser.views.MUserGridViewController");$import("rguser.views.MUserGridViewUserController");
mx.weblets.WebletManager.register({id:"rguser",name:"rguser",requires:[],onload:function(){},onstart:function(a){var b=new rguser.views.MUserGridViewUserController;a.context.rootViewPort.setViewController(b)}});$ns("rguser.views");
rguser.views.MUserGridView=function(){function i(){if(b==null||b.reusable==!1&&b.disposed==!0)b=rguser.context.windowManager.create({entry:!0});b.on("activate",function(){b.setView(a)});b.on("close",function(){$.each(b.controls,function(a,b){b.$e.detach()})})}var a=$extend(mx.views.View),f={};f.init=a.init;a.init=function(){a.permissionID="-1";f.init();c=new mx.containers.HSplit({borderThick:"0",padding:"0",orientation:"horizontal",width:"100%",id:"HSplit",rows:"25,auto",height:"100%"});a.addControl(c);
d=new mx.containers.Container({layout:"mx.layouts.AbsoluteLayout",id:"HSplitArea0"});c.addControl(d,0);g=new mx.controls.ToolBar({itemAlign:"right",width:"100%",layoutConfigs:{},id:"ToolBar",direction:"horizontal",height:"24",items:[{imageKey:"add",name:"NewButton",width:"60",id:"NewButton",text:"\u65b0\u589e",height:"20",onclick:a.controller._NewButton_onclick},{imageKey:"save",name:"SaveButton",width:"60",id:"SaveButton",text:"\u4fdd\u5b58",height:"20",onclick:a.controller._SaveButton_onclick},
{imageKey:"delete",name:"DelButton",width:"60",id:"DelButton",text:"\u5220\u9664",height:"20",onclick:a.controller._DelButton_onclick},{imageKey:"print",width:"60",id:"PrintButton",text:"\u6253\u5370",droppedDown:!1,useSymbol:!0,height:"20",onclick:a.controller._PrintButton_onclick}]});d.addControl(g);e=new mx.containers.Container({layout:"mx.layouts.AbsoluteLayout",id:"HSplitArea1"});c.addControl(e,1);var b=new mx.datacontainers.GridEntityContainer({baseUrl:rguser.mappath("~/rest/mUser/"),loadMeta:!1,
iscID:"-1",primaryKey:"mUserId"});h=new mx.datacontrols.DataGrid({columns:[{dataType:"string",name:"mUserId",width:"120",caption:"\u7528\u6237ID",readOnly:!1,id:"mUserId",editorType:"TextEditor",nullable:!1},{dataType:"string",name:"openId",width:"120",caption:"\u5fae\u4fe1\u7528\u6237\u552f\u4e00\u6807\u8bc6",readOnly:!1,id:"openId",editorType:"TextEditor"},{dataType:"string",name:"areaId",width:"120",caption:"\u5f52\u5c5e\u533a\u57dfID",readOnly:!1,id:"areaId",editorType:"TextEditor"},{dataType:"string",
name:"nickName",width:"120",caption:"\u5fae\u4fe1\u6635\u79f0",readOnly:!1,id:"nickName",editorType:"TextEditor"},{dataType:"string",name:"photoUrl",width:"120",caption:"\u5fae\u4fe1\u5934\u50cfURL",readOnly:!1,id:"photoUrl",editorType:"TextEditor"},{dataType:"string",name:"gender",width:"120",caption:"\u6027\u522b",readOnly:!1,id:"gender",editorType:"TextEditor"},{formatString:"yyyy-MM-dd HH:mm:ss",displayTime:!0,dataType:"timestamp",name:"loginDate",width:"120",caption:"\u6700\u540e\u767b\u9646\u65f6\u95f4",
readOnly:!1,id:"loginDate",editorType:"DateTimeEditor"}],allowEditing:!0,allowPaging:!0,validateOnSaving:!0,pageIndex:1,width:"100%",layoutConfigs:{},pageSize:20,displayCheckBox:!0,id:"DataGrid",height:"100%",pageNaviBar:new mx.datacontrols.PageNaviBar({pageIndex:1,pageSize:20,id:"PageNaviBar1",height:"24"}),entityContainer:b});e.addControl(h);a.on("activate",a.controller._onactivate)};var c=null,d=null,g=null,e=null,h=null,b=null;a.getWindow=function(){i();return b};a.findControlById=function(b){try{return a.findControl("id",
b)}catch(c){return mx.indicate("info","\u672a\u627e\u5230\u5bf9\u5e94\u7684mx\u63a7\u4ef6:    "+c.message),null}};return a.endOfClass(arguments)};$ns("rguser.views");
rguser.views.MUserGridViewController=function(){var a=$extend(mx.views.ViewController);a.getView=function(){if(a.view==null)a.view=new rguser.views.MUserGridView({controller:a});return a.view};if(typeof a.utils=="undefined"||a.utils==null)a.utils={};a.utils.removeDataGridSelections=function(a){a.displayCheckBox?a.getCheckedItems().length==0?mx.indicate("info","\u8bf7\u81f3\u5c11\u52fe\u9009\u4e00\u6761\u5f85\u5220\u9664\u8bb0\u5f55\u3002"):confirm("\u60a8\u786e\u8ba4\u5220\u9664\u6570\u636e\u5417\uff1f")&&a.removeItems(a.getCheckedItems()):
a.selection==null?mx.indicate("info","\u8bf7\u9009\u62e9\u4e00\u6761\u5f85\u5220\u9664\u8bb0\u5f55\u3002"):confirm("\u60a8\u786e\u8ba4\u5220\u9664\u6570\u636e\u5417\uff1f")&&a.removeItem(a.selection)};var b=null;a._onactivate=function(){b=a.getView().findControlById("DataGrid");b.load()};a._NewButton_onclick=function(){b.appendItem()};a._SaveButton_onclick=function(){b.save()};a._DelButton_onclick=function(){a.utils.removeDataGridSelections(b)};a._PrintButton_onclick=function(){b.printGrid(!0)};return a.endOfClass(arguments)};$ns("rguser.views");rguser.views.MUserGridViewUserController=function(){return $extend(rguser.views.MUserGridViewController).endOfClass(arguments)};