$import("mx.containers.VSplit");$import("mx.containers.Container");$import("mx.datacontrols.DataTree");$import("mx.datacontainers.TreeEntityContainer");$import("mx.containers.HSplit");$import("mx.controls.ToolBar");$import("mx.datacontrols.DataForm");$import("mx.datacontainers.FormEntityContainer");$import("mx.windows.Window");$import("etype.views.ExamTypeTreeView");$import("etype.views.ExamTypeTreeViewController");$import("etype.views.ExamTypeTreeViewUserController");
mx.weblets.WebletManager.register({id:"etype",name:"etype",requires:[],onload:function(){},onstart:function(a){var b=new etype.views.ExamTypeTreeViewUserController;a.context.rootViewPort.setViewController(b)}});$ns("etype.views");
etype.views.ExamTypeFormView=function(){function i(){if(a==null||a.reusable==!1&&a.disposed==!0)a=etype.context.windowManager.create({title:"\u8be6\u7ec6\u4fe1\u606f",reusable:!0});a.on("activate",function(){a.setView(b)});a.on("close",function(){$.each(a.controls,function(b,a){a.$e.detach()})})}var b=$extend(mx.views.View),f={};f.init=b.init;b.init=function(){b.permissionID="-1";f.init();c=new mx.containers.HSplit({borderThick:"0",padding:"0",orientation:"horizontal",width:"100%",id:"HSplit",rows:"25,auto",
height:"100%"});b.addControl(c);d=new mx.containers.Container({layout:"mx.layouts.AbsoluteLayout",id:"HSplitArea0"});c.addControl(d,0);g=new mx.controls.ToolBar({itemAlign:"right",width:"100%",layoutConfigs:{},id:"DetailToolBar",direction:"horizontal",height:"24",items:[{imageKey:"save",width:"60",id:"SaveButton",text:"\u4fdd\u5b58",droppedDown:!1,useSymbol:!0,height:"20",onclick:b.controller._saveButton_onclick}]});d.addControl(g);e=new mx.containers.Container({layout:"mx.layouts.AbsoluteLayout",
id:"HSplitArea1"});c.addControl(e,1);var a=new mx.datacontainers.FormEntityContainer({baseUrl:etype.mappath("~/rest/examType/"),loadMeta:!1,iscID:"-1",primaryKey:"examTypeId",meta:[{readOnly:!1,nullable:!0,visible:!0,valueType:"string",name:"parentId",caption:"\u4e0a\u7ea7\u5206\u7c7b"},{readOnly:!1,nullable:!1,visible:!0,valueType:"string",name:"typeName",caption:"\u5206\u7c7b\u540d\u79f0"},{readOnly:!1,nullable:!1,visible:!0,valueType:"string",name:"typeCode",caption:"\u5206\u7c7b\u7f16\u7801"},
{readOnly:!1,nullable:!0,visible:!0,valueType:"string",name:"remarks",caption:"\u5907\u6ce8"}]});h=new mx.datacontrols.DataForm({width:"100%",layoutConfigs:{},id:"DataForm",maxCols:1,height:"100%",fields:[["[\u9ed8\u8ba4]",!0,{lineBreak:!1,name:"parentId",caption:"\u4e0a\u7ea7\u5206\u7c7b",labelWidth:120,readOnly:!1,id:"parentId",height:"22",editorType:"DropDownEditor"},{lineBreak:!1,name:"typeName",caption:"\u5206\u7c7b\u540d\u79f0",labelWidth:120,readOnly:!1,id:"typeName",height:"22",editorType:"TextEditor",
nullable:!1},{lineBreak:!1,name:"typeCode",caption:"\u5206\u7c7b\u7f16\u7801",labelWidth:120,readOnly:!1,id:"typeCode",height:"22",editorType:"TextEditor",nullable:!1},{lineBreak:!1,name:"remarks",caption:"\u5907\u6ce8",textMode:"multiline",labelWidth:120,readOnly:!1,id:"remarks",height:"66",editorType:"TextEditor"}]],entityContainer:a});e.addControl(h);b.on("activate",b.controller._onactivate)};var c=null,d=null,g=null,e=null,h=null,a=null;b.getWindow=function(){i();return a};b.findControlById=function(a){try{return b.findControl("id",
a)}catch(c){return mx.indicate("info","\u672a\u627e\u5230\u5bf9\u5e94\u7684mx\u63a7\u4ef6:    "+c.message),null}};return b.endOfClass(arguments)};$ns("etype.views");
etype.views.ExamTypeFormViewController=function(){var a=$extend(mx.views.ViewController);a.typeName="etype.views.ExamTypeFormViewController";a.getController=function(b){return a.getLinkViewController("etype.views."+b+"Controller")};a.getView=function(){if(a.view==null)a.view=new etype.views.ExamTypeFormView({controller:a});return a.view};var b=null;a._onactivate=function(){b=a.getView().findControlById("DataForm");var c=a.getController("ExamTypeGridView").getView().findControlById("DataGrid");b.entityContainer.on("saved",
function(){a.getView().getWindow().hide();c.load()})};a._saveButton_onclick=function(){b.save()};return a.endOfClass(arguments)};$ns("etype.views");etype.views.ExamTypeFormViewUserController=function(){return $extend(etype.views.ExamTypeFormViewController).endOfClass(arguments)};$ns("etype.views");
etype.views.ExamTypeGridView=function(){function j(){c.load({nodes:[{itemType:"examType",classDisplayName:"ExamType",nodeTextProp:"typeName",className:"ExamType",nodeIDProp:"examTypeId",displayMode:"entityNode",nodes:[]}]})}function k(a){a.node.queryParams=null}function l(){if(b==null||b.reusable==!1&&b.disposed==!0)b=etype.context.windowManager.create({entry:!0});b.on("activate",function(){b.setView(a)});b.on("close",function(){$.each(b.controls,function(a,b){b.$e.detach()})})}var a=$extend(mx.views.View),
g={};g.init=a.init;a.init=function(){a.permissionID="-1";g.init();d=new mx.containers.VSplit({orientation:"vertical",width:"100%",id:"VSplit2",cols:"20%,80%",height:"100%"});a.addControl(d);f=new mx.containers.Container({layout:"mx.layouts.AbsoluteLayout",id:"VSplit2Area0"});d.addControl(f,0);var b=new mx.datacontainers.TreeEntityContainer({baseUrl:etype.mappath("~/rest/examTypeTree/tree"),type:"remote"});c=new mx.datacontrols.DataTree({loadRootNodes:j,size:"[\u5bbd:100% \u9ad8:100%]",top:"-2",left:"1",
width:"100%",x:"1",y:"-2",id:"DataTree",showDefaultContextMenu:!1,height:"100%",entityContainer:b});c.on("nodeclick",a.controller._DataTree_onnodeclick);c.on("expanding",k);c.on("menushowing",m);f.addControl(c);e=new mx.containers.Container({layout:"mx.layouts.AbsoluteLayout",id:"VSplit2Area1"});d.addControl(e,1);b=new mx.datacontainers.GridEntityContainer({baseUrl:etype.mappath("~/rest/examType/"),loadMeta:!1,iscID:"-1",primaryKey:"examTypeId"});h=new mx.datacontrols.DataGrid({searchBox:new mx.datacontrols.DataGridSearchBox({width:"100%",
id:"DataGridSearchBox1",fields:[{lineBreak:!1,valueType:"string",name:"typeName",caption:"\u5206\u7c7b\u540d\u79f0",labelWidth:100,readOnly:!1,id:"typeName",editorType:"TextEditor",height:"22"},{lineBreak:!1,valueType:"string",name:"typeCode",caption:"\u5206\u7c7b\u7f16\u7801",labelWidth:100,readOnly:!1,id:"typeCode",editorType:"TextEditor",height:"22"}]}),columns:[{valueType:"string",dataType:"string",name:"parentId",width:"120",caption:"\u4e0a\u7ea7\u5206\u7c7b",readOnly:!1,id:"parentId",editorType:"DropDownEditor"},
{valueType:"string",dataType:"string",name:"typeName",width:"120",caption:"\u5206\u7c7b\u540d\u79f0",readOnly:!1,id:"typeName",editorType:"TextEditor",nullable:!1},{valueType:"string",dataType:"string",name:"typeCode",width:"120",caption:"\u5206\u7c7b\u7f16\u7801",readOnly:!1,id:"typeCode",editorType:"TextEditor",nullable:!1},{valueType:"string",dataType:"string",name:"remarks",width:"120",caption:"\u5907\u6ce8",textMode:"multiline",readOnly:!1,id:"remarks",editorType:"TextEditor"}],allowEditing:!1,
allowPaging:!0,pageSize:20,pageIndex:1,width:"100%",layoutConfigs:{left:1,top:28},displayCheckBox:!0,id:"DataGrid",height:"93%",pageNaviBar:new mx.datacontrols.PageNaviBar({pageIndex:1,pageSize:20,id:"PageNaviBar1"}),entityContainer:b});e.addControl(h);i=new mx.controls.ToolBar({itemAlign:"right",width:"100%",layoutConfigs:{left:-2,top:-1},id:"ToolBar3",direction:"horizontal",height:"30",items:[{imageKey:"add",name:"NewButton",width:"60",id:"ToolBarItem5",text:"\u65b0\u589e",height:"20",onclick:a.controller._NewButton_onclick},
{imageKey:"edit",width:"60",id:"ToolBarItem6",text:"\u7f16\u8f91",droppedDown:!1,useSymbol:!0,height:"20",onclick:a.controller._EditButton_onclick},{imageKey:"delete",name:"DelButton",width:"60",id:"ToolBarItem7",text:"\u5220\u9664",height:"20",onclick:a.controller._DelButton_onclick}]});e.addControl(i);a.on("activate",a.controller._onactivate)};var d=null,f=null,c=null,e=null,h=null,i=null,b=null,m=function(){};a.getWindow=function(){l();return b};a.findControlById=function(b){try{return a.findControl("id",
b)}catch(c){return mx.indicate("info","\u672a\u627e\u5230\u5bf9\u5e94\u7684mx\u63a7\u4ef6:    "+c.message),null}};return a.endOfClass(arguments)};$ns("etype.views");
etype.views.ExamTypeGridViewController=function(){var a=$extend(mx.views.ViewController);a.typeName="etype.views.ExamTypeGridViewController";a.getController=function(c){return a.getLinkViewController("etype.views."+c+"Controller")};a.getView=function(){if(a.view==null)a.view=new etype.views.ExamTypeGridView({controller:a});return a.view};if(typeof a.utils=="undefined"||a.utils==null)a.utils={};a.utils.showDetailViewWindow=function(a,b,d,e){b.getView().findControlById(d).load(a);a=b.getView().getWindow();
typeof e=="string"&&a.setTitle(e);a.showDialog()};a.utils.removeDataGridSelections=function(a){a.displayCheckBox?a.getCheckedItems().length==0?mx.indicate("info","\u8bf7\u81f3\u5c11\u52fe\u9009\u4e00\u6761\u5f85\u5220\u9664\u8bb0\u5f55\u3002"):confirm("\u60a8\u786e\u8ba4\u5220\u9664\u6570\u636e\u5417\uff1f")&&a.removeItems(a.getCheckedItems()):a.selection==null?mx.indicate("info","\u8bf7\u9009\u62e9\u4e00\u6761\u5f85\u5220\u9664\u8bb0\u5f55\u3002"):confirm("\u60a8\u786e\u8ba4\u5220\u9664\u6570\u636e\u5417\uff1f")&&
a.removeItem(a.selection)};var b=null,d=null;a._onactivate=function(){b=a.getView().findControlById("DataGrid");b.load();d=a.getView().findControlById("DataTree");d.load()};a._DataTree_onnodeclick=function(c){if(a.view.findControlById("DataGrid")!=null&&c.node.itemType=="examType")selectedNode=c.node,b.objID=c.node.id,b.load(b.objID)};a._NewButton_onclick=function(){var b=a.getController("ExamTypeFormView");a.utils.showDetailViewWindow(null,b,"DataForm")};a._DelButton_onclick=function(){a.utils.removeDataGridSelections(b)};
a._EditButton_onclick=function(){if(b.selection==null)mx.indicate("info","\u8bf7\u9009\u62e9\u4e00\u6761\u5f85\u7f16\u8f91\u8bb0\u5f55\u3002");else{var c=b.selection.getValue(b.entityContainer.primaryKey),d=a.getController("ExamTypeFormView");a.utils.showDetailViewWindow(c,d,"DataForm")}};a._DataGrid_onitemdoubleclick=function(){a._EditButton_onclick()};a._PrintButton_onclick=function(){b.printGrid(!0)};a._ToolBar3_btn_add_onclick=function(){var b=a.getController("ExamTypeFormView");a.utils.showDetailViewWindow(null,
b,"DataForm")};a._ToolBar3_btn_update_onclick=function(){if(b.selection==null)mx.indicate("info","\u8bf7\u9009\u62e9\u4e00\u6761\u5f85\u7f16\u8f91\u8bb0\u5f55\u3002");else{var c=b.selection.getValue(b.entityContainer.primaryKey),d=a.getController("ExamTypeFormView");a.utils.showDetailViewWindow(c,d,"DataForm")}};a._ToolBar3_btn_delete_onclick=function(){a.utils.removeDataGridSelections(b)};a._ToolBar3_btn_query_onclick=function(){};return a.endOfClass(arguments)};$ns("etype.views");etype.views.ExamTypeGridViewUserController=function(){return $extend(etype.views.ExamTypeGridViewController).endOfClass(arguments)};