$import("mx.containers.HSplit");$import("mx.containers.Container");$import("mx.controls.ToolBar");$import("mx.datacontrols.DataGrid");$import("mx.datacontainers.GridEntityContainer");$import("mx.datacontrols.PageNaviBar");$import("mx.windows.Window");$import("readtext.views.ReadingTextGridView");$import("readtext.views.ReadingTextGridViewController");$import("readtext.views.ReadingTextGridViewUserController");$import("mx.datacontrols.DataForm");$import("mx.datacontainers.FormEntityContainer");$import("readtext.views.ReadingTextFormView");
$import("readtext.views.ReadingTextFormViewController");$import("readtext.views.ReadingTextFormViewUserController");mx.weblets.WebletManager.register({id:"readtext",name:"readtext",requires:[],onload:function(){},onstart:function(a){var b=new readtext.views.ReadingTextGridViewUserController;a.context.rootViewPort.setViewController(b)}});$ns("readtext.views");
readtext.views.ReadingTextFormView=function(){function i(){if(a==null||a.reusable==!1&&a.disposed==!0)a=readtext.context.windowManager.create({title:"\u8be6\u7ec6\u4fe1\u606f",reusable:!0});a.on("activate",function(){a.setView(b)});a.on("close",function(){$.each(a.controls,function(b,a){a.$e.detach()})})}var b=$extend(mx.views.View),f={};f.init=b.init;b.init=function(){b.permissionID="-1";f.init();c=new mx.containers.HSplit({borderThick:"0",padding:"0",orientation:"horizontal",width:"100%",id:"HSplit",
rows:"25,auto",height:"100%"});b.addControl(c);d=new mx.containers.Container({layout:"mx.layouts.AbsoluteLayout",id:"HSplitArea0"});c.addControl(d,0);g=new mx.controls.ToolBar({itemAlign:"right",width:"100%",layoutConfigs:{},id:"DetailToolBar",direction:"horizontal",height:"24",items:[{imageKey:"save",width:"60",id:"SaveButton",text:"\u4fdd\u5b58",droppedDown:!1,useSymbol:!0,height:"20",onclick:b.controller._saveButton_onclick}]});d.addControl(g);e=new mx.containers.Container({layout:"mx.layouts.AbsoluteLayout",
id:"HSplitArea1"});c.addControl(e,1);var a=new mx.datacontainers.FormEntityContainer({baseUrl:readtext.mappath("~/rest/readingText/"),loadMeta:!1,iscID:"-1",primaryKey:"readingId",meta:[{readOnly:!1,nullable:!1,visible:!0,valueType:"string",name:"readingId",caption:"\u9605\u8bfb\u5185\u5bb9ID"},{readOnly:!1,nullable:!1,visible:!0,valueType:"string",name:"readingCode",caption:"\u9605\u8bfb\u5185\u5bb9\u7f16\u7801"},{readOnly:!1,nullable:!1,visible:!0,valueType:"string",name:"readingImg",caption:"\u9605\u8bfb\u56fe\u7247\u5185\u5bb9"},
{readOnly:!1,nullable:!1,visible:!0,valueType:"string",name:"readingText",caption:"\u9605\u8bfb\u6587\u672c\u5185\u5bb9"}]});h=new mx.datacontrols.DataForm({width:"100%",layoutConfigs:{},id:"DataForm",maxCols:1,height:"100%",fields:[["[\u9ed8\u8ba4]",!0,{lineBreak:!1,name:"readingId",caption:"\u9605\u8bfb\u5185\u5bb9ID",labelWidth:120,readOnly:!1,id:"readingId",height:"22",editorType:"TextEditor",nullable:!1},{lineBreak:!1,name:"readingCode",caption:"\u9605\u8bfb\u5185\u5bb9\u7f16\u7801",labelWidth:120,
readOnly:!1,id:"readingCode",height:"22",editorType:"TextEditor",nullable:!1},{lineBreak:!1,name:"readingImg",caption:"\u9605\u8bfb\u56fe\u7247\u5185\u5bb9",labelWidth:120,readOnly:!1,id:"readingImg",height:"22",editorType:"TextEditor",nullable:!1},{lineBreak:!1,name:"readingText",caption:"\u9605\u8bfb\u6587\u672c\u5185\u5bb9",labelWidth:120,readOnly:!1,id:"readingText",height:"100",editorType:"RichTextEditor",nullable:!1}]],entityContainer:a});e.addControl(h);b.on("activate",b.controller._onactivate)};
var c=null,d=null,g=null,e=null,h=null,a=null;b.getWindow=function(){i();return a};b.findControlById=function(a){try{return b.findControl("id",a)}catch(c){return mx.indicate("info","\u672a\u627e\u5230\u5bf9\u5e94\u7684mx\u63a7\u4ef6:    "+c.message),null}};return b.endOfClass(arguments)};$ns("readtext.views");
readtext.views.ReadingTextFormViewController=function(){var a=$extend(mx.views.ViewController);a.typeName="readtext.views.ReadingTextFormViewController";a.getController=function(b){return a.getLinkViewController("readtext.views."+b+"Controller")};a.getView=function(){if(a.view==null)a.view=new readtext.views.ReadingTextFormView({controller:a});return a.view};var b=null;a._onactivate=function(){b=a.getView().findControlById("DataForm");var c=a.getController("ReadingTextGridView").getView().findControlById("DataGrid");b.entityContainer.on("saved",
function(){a.getView().getWindow().hide();c.load()})};a._saveButton_onclick=function(){console.log("save clicked");b.save()};return a.endOfClass(arguments)};$ns("readtext.views");readtext.views.ReadingTextFormViewUserController=function(){return $extend(readtext.views.ReadingTextFormViewController).endOfClass(arguments)};$ns("readtext.views");
readtext.views.ReadingTextGridView=function(){function i(){if(b==null||b.reusable==!1&&b.disposed==!0)b=readtext.context.windowManager.create({entry:!0});b.on("activate",function(){b.setView(a)});b.on("close",function(){$.each(b.controls,function(a,b){b.$e.detach()})})}var a=$extend(mx.views.View),g={};g.init=a.init;a.init=function(){a.permissionID="-1";g.init();c=new mx.containers.HSplit({borderThick:"0",padding:"0",orientation:"horizontal",width:"100%",id:"HSplit",rows:"25,auto",height:"100%"});
a.addControl(c);e=new mx.containers.Container({layout:"mx.layouts.AbsoluteLayout",id:"HSplitArea0"});c.addControl(e,0);h=new mx.controls.ToolBar({itemAlign:"right",width:"100%",layoutConfigs:{},id:"MainToolBar",direction:"horizontal",height:"24",items:[{imageKey:"add",width:"60",id:"NewButton",text:"\u65b0\u5efa",droppedDown:!1,useSymbol:!0,height:"20",onclick:a.controller._NewButton_onclick},{imageKey:"delete",width:"60",id:"DelButton",text:"\u5220\u9664",droppedDown:!1,useSymbol:!0,height:"20",
onclick:a.controller._DelButton_onclick},{imageKey:"edit",width:"60",id:"EditButton",text:"\u7f16\u8f91",droppedDown:!1,useSymbol:!0,height:"20",onclick:a.controller._EditButton_onclick},{imageKey:"print",width:"60",id:"PrintButton",text:"\u6253\u5370",droppedDown:!1,useSymbol:!0,height:"20",onclick:a.controller._PrintButton_onclick}]});e.addControl(h);f=new mx.containers.Container({layout:"mx.layouts.AbsoluteLayout",id:"HSplitArea1"});c.addControl(f,1);var b=new mx.datacontainers.GridEntityContainer({baseUrl:readtext.mappath("~/rest/readingText/"),
loadMeta:!1,iscID:"-1",primaryKey:"readingId"});d=new mx.datacontrols.DataGrid({columns:[{valueType:"string",dataType:"string",name:"readingId",width:"120",caption:"\u9605\u8bfbsd\u5185\u5bb9ID",readOnly:!1,id:"readingId",editorType:"TextEditor"},{valueType:"string",dataType:"string",name:"readingCode",width:"120",caption:"\u9605\u8bfb\u5185\u5bb9\u7f16\u7801",readOnly:!1,id:"readingCode",editorType:"TextEditor"},{valueType:"string",dataType:"string",name:"readingImg",width:"25%",caption:"\u9605\u8bfb\u56fe\u7247\u5185\u5bb9",
readOnly:!1,id:"readingImg",editorType:"TextEditor"},{valueType:"string",dataType:"string",name:"readingText",width:"25%",caption:"\u9605\u8bfb\u6587\u672c\u5185\u5bb9",readOnly:!1,id:"readingText",editorType:"RichTextEditor"}],allowEditing:!1,allowPaging:!0,pageIndex:1,width:"100%",layoutConfigs:{},pageSize:20,displayCheckBox:!0,id:"DataGrid",height:"100%",pageNaviBar:new mx.datacontrols.PageNaviBar({pageIndex:1,pageSize:20,id:"PageNaviBar",height:"50"}),entityContainer:b});d.on("itemclick",a.controller._DataGrid_onitemdoubleclick);
d.on("itemchecked",a.controller._DataGrid_onitemchecked);f.addControl(d);a.on("activate",a.controller._onactivate)};var c=null,e=null,h=null,f=null,d=null,b=null;a.getWindow=function(){i();return b};a.findControlById=function(b){try{return a.findControl("id",b)}catch(c){return mx.indicate("info","\u672a\u627e\u5230\u5bf9\u5e94\u7684mx\u63a7\u4ef6:    "+c.message),null}};return a.endOfClass(arguments)};$ns("readtext.views");
readtext.views.ReadingTextGridViewController=function(){var a=$extend(mx.views.ViewController);a.typeName="readtext.views.ReadingTextGridViewController";a.getController=function(c){return a.getLinkViewController("readtext.views."+c+"Controller")};a.getView=function(){if(a.view==null)a.view=new readtext.views.ReadingTextGridView({controller:a});return a.view};if(typeof a.utils=="undefined"||a.utils==null)a.utils={};a.utils.showDetailViewWindow=function(a,b,f,d){b.getView().findControlById(f).load(a);a=
b.getView().getWindow();typeof d=="string"&&a.setTitle(d);a.showDialog()};a.utils.removeDataGridSelections=function(a){a.displayCheckBox?a.getCheckedItems().length==0?mx.indicate("info","\u8bf7\u81f3\u5c11\u52fe\u9009\u4e00\u6761\u5f85\u5220\u9664\u8bb0\u5f55\u3002"):confirm("\u60a8\u786e\u8ba4\u5220\u9664\u6570\u636e\u5417\uff1f")&&a.removeItems(a.getCheckedItems()):a.selection==null?mx.indicate("info","\u8bf7\u9009\u62e9\u4e00\u6761\u5f85\u5220\u9664\u8bb0\u5f55\u3002"):confirm("\u60a8\u786e\u8ba4\u5220\u9664\u6570\u636e\u5417\uff1f")&&
a.removeItem(a.selection)};var b=null;a._onactivate=function(){b=a.getView().findControlById("DataGrid");b.load()};a._NewButton_onclick=function(){var b=a.getController("ReadingTextFormView");a.utils.showDetailViewWindow(null,b,"DataForm")};a._DelButton_onclick=function(){a.utils.removeDataGridSelections(b)};a._EditButton_onclick=function(){if(b.getCheckedItems().length!=1)mx.indicate("info","\u8bf7\u9009\u62e9\u4e00\u6761\u5f85\u7f16\u8f91\u8bb0\u5f55");else{console.log("edit selected.");var c=b.entityContainer.primaryKey;
console.log(c);var c=b.getCheckedItems()[0].getValue(c),e=a.getController("ReadingTextFormView");a.utils.showDetailViewWindow(c,e,"DataForm")}};a._DataGrid_onitemdoubleclick=function(){};a._DataGrid_onitemchecked=function(){};a._PrintButton_onclick=function(){b.printGrid(!0)};return a.endOfClass(arguments)};$ns("readtext.views");readtext.views.ReadingTextGridViewUserController=function(){return $extend(readtext.views.ReadingTextGridViewController).endOfClass(arguments)};