$import("mx.containers.VSplit");$import("mx.containers.Container");$import("mx.datacontrols.DataTree");$import("mx.datacontainers.TreeEntityContainer");$import("mx.containers.HSplit");$import("mx.controls.ToolBar");$import("mx.datacontrols.DataForm");$import("mx.datacontainers.FormEntityContainer");$import("mx.windows.Window");$import("etTree.views.ExamTypeTreeView");$import("etTree.views.ExamTypeTreeViewController");$import("etTree.views.ExamTypeTreeViewUserController");
mx.weblets.WebletManager.register({id:"etTree",name:"etTree",requires:[],onload:function(){},onstart:function(a){var b=new etTree.views.ExamTypeTreeViewUserController;a.context.rootViewPort.setViewController(b)}});$ns("etTree.views");
etTree.views.ExamTypeTreeView=function(){function m(){c.load({nodes:[{itemType:"70fc383b-622c-4eb7-9ed7-11f09e30e65f",classDisplayName:"ExamType",nodeTextProp:"typeName",className:"ExamType",nodeIDProp:"examTypeId",displayMode:"entityNode",nodes:[]}]})}function n(a){a.node.queryParams=null}function o(){if(b==null||b.reusable==!1&&b.disposed==!0)b=etTree.context.windowManager.create({entry:!0});b.on("activate",function(){b.setView(a)});b.on("close",function(){$.each(b.controls,function(a,b){b.$e.detach()})})}
var a=$extend(mx.views.View),j={};j.init=a.init;a.init=function(){a.permissionID="-1";j.init();d=new mx.containers.VSplit({borderThick:"0",orientation:"vertical",resizable:!0,width:"100%",id:"VSplit",cols:"20%,auto",height:"100%"});a.addControl(d);f=new mx.containers.Container({id:"VSplitArea0"});d.addControl(f,0);var b=new mx.datacontainers.TreeEntityContainer({baseUrl:etTree.mappath("~/rest/examTypeTree/tree"),type:"remote"});c=new mx.datacontrols.DataTree({loadRootNodes:m,width:"100%",id:"DataTree",
nodeMenu:{items:[{name:"new",text:"\u65b0\u5efa"},{name:"delete",text:"\u5220\u9664",imageKey:"delete"}],onitemclick:a.controller._contextMenuItem_click},showDefaultContextMenu:!1,height:"100%",entityContainer:b});c.on("nodeclick",a.controller._DataTree_onnodeclick);c.on("expanding",n);c.on("menushowing",p);f.addControl(c);g=new mx.containers.Container({id:"VSplitArea1"});d.addControl(g,1);e=new mx.containers.HSplit({borderThick:"0",padding:"0",orientation:"horizontal",width:"100%",id:"HSplit",rows:"25,auto",
height:"100%"});g.addControl(e);h=new mx.containers.Container({layout:"mx.layouts.AbsoluteLayout",id:"HSplitArea0"});e.addControl(h,0);k=new mx.controls.ToolBar({itemAlign:"right",width:"100%",layoutConfigs:{},id:"ToolBar",direction:"horizontal",height:"24",items:[{imageKey:"save",name:"save",width:"60",toolTip:"\u4fdd\u5b58",id:"saveButton",text:"\u4fdd\u5b58",height:"20",onclick:a.controller._saveButton_onclick}]});h.addControl(k);i=new mx.containers.Container({layout:"mx.layouts.AbsoluteLayout",
id:"HSplitArea1"});e.addControl(i,1);b=new mx.datacontainers.FormEntityContainer({baseUrl:etTree.mappath("~/rest/examType/"),loadMeta:!1,iscID:"-1",primaryKey:"examTypeId",meta:[{readOnly:!1,nullable:!0,visible:!0,valueType:"string",name:"parentId",caption:"\u7236\u7ea7\u7f16\u53f7"},{readOnly:!1,nullable:!1,visible:!0,valueType:"string",name:"typeName",caption:"\u5206\u7c7b\u540d\u79f0"},{readOnly:!1,nullable:!1,visible:!0,valueType:"string",name:"typeCode",caption:"\u5206\u7c7b\u7f16\u7801"},{readOnly:!1,
nullable:!0,visible:!0,valueType:"string",name:"remarks",caption:"\u5907\u6ce8"}]});l=new mx.datacontrols.DataForm({width:"100%",layoutConfigs:{},id:"DataForm",maxCols:1,height:"100%",fields:[["[\u9ed8\u8ba4]",!0,{lineBreak:!1,valueType:"string",name:"parentId",caption:"\u4e0a\u7ea7\u5206\u7c7b",labelWidth:120,readOnly:!1,id:"parentId",height:"22",editorType:"DropDownEditor"},{lineBreak:!1,valueType:"string",name:"typeName",caption:"\u5206\u7c7b\u540d\u79f0",labelWidth:120,readOnly:!1,id:"typeName",
height:"22",editorType:"TextEditor",nullable:!1},{lineBreak:!1,valueType:"string",name:"typeCode",caption:"\u5206\u7c7b\u7f16\u7801",labelWidth:120,readOnly:!1,id:"typeCode",height:"22",editorType:"TextEditor",nullable:!1},{lineBreak:!1,valueType:"string",name:"remarks",caption:"\u5907\u6ce8",textMode:"multiline",labelWidth:120,readOnly:!1,id:"remarks",height:"66",editorType:"TextEditor"}]],entityContainer:b});i.addControl(l);a.on("activate",a.controller._onactivate)};var d=null,f=null,c=null,g=null,
e=null,h=null,k=null,i=null,l=null,b=null;a.getTreeView=function(){return c};var p=function(){};a.getWindow=function(){o();return b};a.findControlById=function(b){try{return a.findControl("id",b)}catch(c){return mx.indicate("info","\u672a\u627e\u5230\u5bf9\u5e94\u7684mx\u63a7\u4ef6:    "+c.message),null}};return a.endOfClass(arguments)};$ns("etTree.views");
etTree.views.ExamTypeTreeViewController=function(){function f(){if(a.view.getTreeView().selection){var b=a.view.getTreeView().selection;b!=null&&confirm("\u60a8\u786e\u8ba4\u5220\u9664\u6570\u636e\u5417\uff1f")&&(new mx.rpc.RESTClient({baseUrl:etTree.mappath("~/rest/examType")})).post("/deleteById?id="+b.id,function(b){b.successful?(mx.indicate("info","\u5220\u9664\u6210\u529f\uff01"),a.view.findControlById("DataTree").load(),c=a.getView().findControlById("DataForm"),c.load()):mx.indicate("info",
"\u5220\u9664\u5931\u8d25\uff01")})}}var a=$extend(mx.views.ViewController);a.getView=function(){if(a.view==null)a.view=new etTree.views.ExamTypeTreeView({controller:a});return a.view};var c=null;a._onactivate=function(){a.view.findControlById("DataTree").loadRootNodes();var b=a.view.findControlById("DataForm");b.entityContainer.on("saved",function(){mx.indicate("info","\u4fdd\u5b58\u6210\u529f");var d=a.view.findControlById("DataTree");d.load();var c=b.getEditor("typeName"),e=null;$notEmpty(c)&&
(e=c.getValue());$notEmpty(d)&&$notEmpty(d.selection)&&$notEmpty(e)&&d.selection.setText(e)});c=a.getView().findControlById("DataForm");c.load()};a._DataTree_onnodeclick=function(b){var c=a.view.findControlById("DataForm");if(c!=null&&b.node.itemType=="examType")c.objID=b.node.id,c.load(c.objID)};a._contextMenuItem_click=function(b){switch(b.item.name){case "refresh":if(a.view.getTreeView().selection)b=a.view.getTreeView().selection,b!=null&&b.refresh();break;case "new":c=a.getView().findControlById("DataForm");
c.load();break;case "delete":f()}};a._saveButton_onclick=function(){a.view.findControlById("DataForm").save()};return a.endOfClass(arguments)};$ns("etTree.views");etTree.views.ExamTypeTreeViewUserController=function(){return $extend(etTree.views.ExamTypeTreeViewController).endOfClass(arguments)};